services:
  # Combined Frontend + Backend Service
  - type: web
    name: ecfr-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health 